#!/bin/bash
set -u

. "$(dirname $0)/backupconfig.sh"
commitBackupRequest="$(dirname $0)/commitBackupRequest"

op="$1"
backup_srv="$2"

case "$op" in
	git)
		find "$git_base" -type d -name '*.git' -exec \
		  "$commitBackupRequest" git {} "$backup_srv" \;
		;;
#	postgresdb)
#		"$commitBackupRequest" "postgresdb" "" "$backup_srv"
#		;;
	trac|wiki|wordpress)
		"$commitBackupRequest" "$op" `eval echo \\$$op` "$backup_srv"
		;;
	apt)
		for dist_repo in $dists_repos
		do
			"$commitBackupRequest" "rsync" "$dist_repo" "$backup_srv"
		done
		;;
	*)
		echo "Unknown OP $op"
		exit 1
esac

