#!/bin/bash
set -eu

source_dir="$1"

name=$(echo -n "$source_dir" | base64)
timestamp=$(date +%y-%m-%d_%H_%M_%S)

echo "backup_dir: \"$source_dir\" successfully"
add_queue "$name" "rsync ${timestamp} ${Export_ssh}:${source_dir}"

