#!/bin/bash
set -eu

git_repo="$1"

git_base="$(dirname "${git_base}/dummy")/"
git_repo="${git_repo/#${git_base}/}"

name=$(echo -n "$git_repo" | base64)

add_queue "$name" "git ${Export_git}/${git_repo}"

