#!/bin/bash
set -eu

git_repo="$1"

git_base="$(dirname "${git_base}/dummy")/"
git_repo="${git_repo/#${git_base}/}"

name=$(base64<<EOF
$git_repo
EOF)

add_queue "$name" "git ${Export_git}/${git_repo}"

